#!/bin/sh 
#
# Reithproxies script = sets up my mac for working on or off Reith

# Always use my .bashrc 
. ~/.bashrc

networkLocation=$(networksetup -getcurrentlocation)

# ON NETWORK SETTINGS
if [[ "$networkLocation" = "BBC On Network" && "$http_proxy" == "" ]]
then
    echo "BBC On Network"
    localeName=work
    . ~/.reithproxies

    # Stop stunnel
    killall stunnel

    echo "Changing SVN settings"
    ln -sf /Volumes/SecureDrive/subversion/servers.$localeName /Volumes/SecureDrive/subversion/servers

    echo "Changing Stunnel settings"
    ln -sf /Volumes/SecureDrive/stunnel/stunnel-$localeName.conf /Volumes/SecureDrive/stunnel/stunnel.conf
    stunnel
fi

# OFF NETWORK SETTINGS
if [[ "$networkLocation" = "BBC Off Network" && "$http_proxy" != "" ]]
then
    echo "BBC Off Network"
    localeName=home
    . ~/.removeproxies

    # Stop stunnel
    killall stunnel

    echo "Changing SVN settings"
    ln -sf /Volumes/SecureDrive/subversion/servers.$localeName /Volumes/SecureDrive/subversion/servers

    echo "Changing Stunnel settings"
    ln -sf /Volumes/SecureDrive/stunnel/stunnel-$localeName.conf /Volumes/SecureDrive/stunnel/stunnel.conf
    stunnel
fi
